### ISSUE TITLE
Text readability

### ISSUE THREAD

**Issue by simon-off** [simonsamples777/burgerboners#1]
# Hello 😩

The pink text on top of the beige burger bun is _kinda hard to read..._

**Please fix!**

![image](https://github.com/simonsamples777/burgerboners/assets/82451181/aa52439f-f15c-45d9-83db-4e4a16f11956)

**Comment by ViggoValfridsson** [comment]
Will work on this thanks

**Comment by ViggoValfridsson** [comment]
That is a stylistic choice bro

**Comment by andreaskostet** [comment]
Absolutely LOVE the fast response from the devs. Keep it up boys.

**Comment by simon-off** [comment]
all talk no walk...
